"""empty message

Revision ID: 4570beba0f7b
Revises: 79273de820c8
Create Date: 2025-06-17 23:28:11.697098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4570beba0f7b'
down_revision = '79273de820c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensagem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensagem', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
