"""empty message

Revision ID: e7123cd7aa05
Revises: 1872c10fb1f6
Create Date: 2025-08-07 17:12:49.807020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7123cd7aa05'
down_revision = '1872c10fb1f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfil', sa.String(length=10), nullable=False))
        batch_op.drop_column('admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('perfil')

    # ### end Alembic commands ###
